### PR TITLE
Update project

### PR DESCRIPTION
**Pull request by IgorGanapolsky**
Updated gradle version.
Updated gradle plugin version.
Used static analysis to fix lint errors.
Added .gitignore files.

### CODE REVIEW

**Comment by lgvalle** [comment]
Hi, can you please provide a description for this PR?

**Comment by IgorGanapolsky** [comment]
@lgvalle done

**Comment by lgvalle** [comment]
Hi @IgorGanapolsky, sorry for the delay.
I appreciate your time and effort to make these lint checks fixes and I'm happy to merge them. 

However I prefer to keep gradle build tools at latest stable version (`1.5.0` today)  I know `2.0.0-alpha8` is working fine for this demo project, but it will be outdated in the near future and is not really adding any value on a project like this.

If you want to amend the PR to keep it at `1.5.0` I'll just merge afterwards. 

Otherwise I can merge as it is and change it myself. 
Whatever you prefer.

**Comment by IgorGanapolsky** [comment]
If you can merge and change yourself, that would be best.

@lgvalle Thanks and keep up the good work.  @changetip $1

**Comment by changetip** [comment]
Hi @lgvalle, @IgorGanapolsky sent you a tip worth 2,674 bits ($1.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/938651)**.



**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Pull request merged**
